### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by PhongTong** [uagrace/like-dislike#1]
It doesn't seem to work with Chrome on WIn Xp. Click it and the counter still remain. Firefox is fine but after reload, the like counter returns to 0.

**Comment by uagrace** [comment]
It doesn't store and doesn't consider a total count of likes and dislikes. Therefore, if you reload page, the plugin will forget the previous state. The total counts should be stored in a database (or any other storage). See [here](http://programmers.stackexchange.com/questions/149352/voting-system-like-stack-exchange).

**Comment by uagrace** [comment]
You should store the total counts in the database
